fix bugs

diff --git a/backup_dir_cron b/backup_dir_cron
--- a/backup_dir_cron
+++ b/backup_dir_cron
@@ -5,28 +5,30 @@ rotate() {
 	local maxbytes=$2
 	local rotate=$3
 
-	if [[ $(du -sb $LOG_FILE) -ge $maxbytes ]]
+	if [ -f $log_file"."$rotate".gz" ]
 	then
-		if [[ -f $log_file.$rotate.gz ]]
-		then
-	    		rm $log_file.$rotate.gz
-  		fi
-	
-		i=1
-		while [[ $i -le $rotate ]]
+		rm $log_file"."$rotate".gz"
+	fi
+
+	if [ "$(du -sb $LOG_FILE | cut -f1)" -ge "$maxbytes" ]
+	then		
+		local i=$rotate	
+		while [ "$i" -ne 0 ]
 		do
-			if [[ -f $log_file.$i.gz ]]
+			if [ -f $log_file"."$i".gz" ]
 			then
-				mv $log_file.$i.gz $log_file.$(($i+1)).gz
+				mv $log_file"."$i".gz" $log_file"."$(($i+1))".gz"
     			fi
-			let i=$i+1
+			let i=$i-1
   		done
 	
-		gzip -c $LOG_FILE > $LOG_FILE"."1.gz
+		gzip -c $log_file > $log_file"."1.gz
+		cat /dev/null > $log_file
 	fi
 }
 
-if [ -f $1 ]	
+
+if [ "$#" -eq 1 ] && [ -f "$1" ]
 then
 	CONF_FILE=$1
 	. $1
@@ -44,11 +46,17 @@ else
 	exit 1
 fi
 
-logger "backup_dir create $(dirname LOG_FILE)"
-[ -d $(dirname $LOG_FILE) ] || \
-	logger "backup_dir $(mkdir -p $(dirname $LOG_FILE))" && exit 1
+rotate $LOG_FILE $LOG_FILE_MAXBYTES $LOG_FILE_ROTATE
 
-[ -w $LOG_FILE ] || logger "can't write to $LOG_FILE" && exit 1
+logger "backup_dir create $(dirname $LOG_FILE)"
+[ -d $(dirname $LOG_FILE) ] || mkdir -p $(dirname $LOG_FILE) || \
+	logger "can't create to $(dirname $LOG_FILE)"
+
+if [ ! -w $(dirname $LOG_FILE) ]
+then
+	logger "can't write to $(dirname $LOG_FILE)"
+	exit 1
+fi
 
 if [ -f ./backup_dir ]	
 then
@@ -61,9 +69,11 @@ else
 	exit 1
 fi
 
-$EXEC $CONF_FILE >> $LOG_FILE
-	#mail -s "[$HOSTNAME] backup_dir failed" -a $LOG_FILE -r $FROM_MAIL $MAIL && exit 1
-
-rotate $LOG_FILE $LOG_FILE_MAXBYTES $LOG_FILE_ROTATE
+logger "backup_dir launch $EXEC $CONF_FILE"
+$EXEC $CONF_FILE >> $LOG_FILE  2>&1;
+if [ $? -ne 0 ]
+then
+	echo "log" | mail -s "[$HOSTNAME] backup_dir failed" -a $LOG_FILE $FROM_MAIL $MAIL
+fi
 
 exit 0
